-- config/main.lua
require('config.plugins')
require('config.nvim-treesitter')
require('config.keybindings')
require('config.colorscheme')
require('config.comments')
require('config.statusline')
require('config.fuzzyfinder')
require('config.gitsigns')
require('config.whichkey')
require('config.lsp')
require('config.fileexplorer')
require('config.nvim-autopairs')
